import { VariableInfo, RegionInfo } from '@/types';

export const VARIABLES: Record<string, VariableInfo> = {
  tmp: {
    code: 'tmp',
    name: 'Mean Temperature',
    unit: '°C',
    icon: '🌡️',
    color: '#FF6B6B',
    description: 'Average air temperature at 2m height',
    normalRange: [-20, 40],
    impactFactor: 8.5,
    climateSensitivity: 'High',
  },
  tmx: {
    code: 'tmx',
    name: 'Maximum Temperature',
    unit: '°C',
    icon: '🔥',
    color: '#FF4757',
    description: 'Daily maximum temperature at 2m height',
    normalRange: [-10, 50],
    impactFactor: 9.0,
    climateSensitivity: 'High',
  },
  tmn: {
    code: 'tmn',
    name: 'Minimum Temperature',
    unit: '°C',
    icon: '❄️',
    color: '#3742FA',
    description: 'Daily minimum temperature at 2m height',
    normalRange: [-30, 30],
    impactFactor: 8.0,
    climateSensitivity: 'High',
  },
  pre: {
    code: 'pre',
    name: 'Precipitation',
    unit: 'mm/month',
    icon: '🌧️',
    color: '#2ED573',
    description: 'Monthly precipitation total',
    normalRange: [0, 500],
    impactFactor: 7.5,
    climateSensitivity: 'Medium',
  },
  cld: {
    code: 'cld',
    name: 'Cloud Cover',
    unit: '%',
    icon: '☁️',
    color: '#A4B0BE',
    description: 'Cloud cover percentage',
    normalRange: [0, 100],
    impactFactor: 5.0,
    climateSensitivity: 'Medium',
  },
  dtr: {
    code: 'dtr',
    name: 'Diurnal Temp Range',
    unit: '°C',
    icon: '📊',
    color: '#FFA502',
    description: 'Daily temperature range (max-min)',
    normalRange: [0, 30],
    impactFactor: 6.5,
    climateSensitivity: 'Medium',
  },
  wet: {
    code: 'wet',
    name: 'Wet Days',
    unit: 'days/month',
    icon: '💧',
    color: '#1E90FF',
    description: 'Number of wet days per month',
    normalRange: [0, 31],
    impactFactor: 6.0,
    climateSensitivity: 'Medium',
  },
  vap: {
    code: 'vap',
    name: 'Vapor Pressure',
    unit: 'hPa',
    icon: '💨',
    color: '#9C88FF',
    description: 'Atmospheric vapor pressure',
    normalRange: [0, 50],
    impactFactor: 7.0,
    climateSensitivity: 'Medium',
  },
  pet: {
    code: 'pet',
    name: 'Evapotranspiration',
    unit: 'mm/month',
    icon: '🌿',
    color: '#F8B500',
    description: 'Potential evapotranspiration',
    normalRange: [0, 200],
    impactFactor: 7.5,
    climateSensitivity: 'High',
  },
  frs: {
    code: 'frs',
    name: 'Frost Days',
    unit: 'days/month',
    icon: '🧊',
    color: '#70A1FF',
    description: 'Number of frost days per month',
    normalRange: [0, 31],
    impactFactor: 6.0,
    climateSensitivity: 'Medium',
  },
};

export const REGIONS: Record<string, RegionInfo> = {
  E2000: {
    code: 'E2000',
    name: 'Eastern Valleys',
    range: '0-2000m',
    icon: '🏞️',
    color: '#FF6B6B',
    climateZone: 'Subtropical',
    vulnerabilityIndex: 7.2,
    biodiversity: 'High',
    glacierCoverage: 'Low',
    elevationProfile: [300, 1200, 2000],
  },
  E4000: {
    code: 'E4000',
    name: 'Eastern Hills',
    range: '2001-4000m',
    icon: '⛰️',
    color: '#FF5722',
    climateZone: 'Temperate',
    vulnerabilityIndex: 6.8,
    biodiversity: 'Very High',
    glacierCoverage: 'Medium',
    elevationProfile: [2001, 3000, 4000],
  },
  E6000: {
    code: 'E6000',
    name: 'Eastern Peaks',
    range: '4001m+',
    icon: '🏔️',
    color: '#FF3D00',
    climateZone: 'Alpine',
    vulnerabilityIndex: 5.5,
    biodiversity: 'Medium',
    glacierCoverage: 'High',
    elevationProfile: [4001, 5200, 6000],
  },
  C2000: {
    code: 'C2000',
    name: 'Central Valleys',
    range: '0-2000m',
    icon: '🏞️',
    color: '#4CAF50',
    climateZone: 'Subtropical',
    vulnerabilityIndex: 8.1,
    biodiversity: 'High',
    glacierCoverage: 'Low',
    elevationProfile: [500, 1500, 2000],
  },
  C4000: {
    code: 'C4000',
    name: 'Central Hills',
    range: '2001-4000m',
    icon: '⛰️',
    color: '#388E3C',
    climateZone: 'Temperate',
    vulnerabilityIndex: 7.5,
    biodiversity: 'High',
    glacierCoverage: 'Medium',
    elevationProfile: [2001, 3500, 4000],
  },
  C6000: {
    code: 'C6000',
    name: 'Central Peaks',
    range: '4001m+',
    icon: '🏔️',
    color: '#2E7D32',
    climateZone: 'Alpine',
    vulnerabilityIndex: 6.3,
    biodiversity: 'Medium',
    glacierCoverage: 'High',
    elevationProfile: [4001, 5500, 8848],
  },
  W2000: {
    code: 'W2000',
    name: 'Western Valleys',
    range: '0-2000m',
    icon: '🏞️',
    color: '#2196F3',
    climateZone: 'Arid Subtropical',
    vulnerabilityIndex: 6.9,
    biodiversity: 'Medium',
    glacierCoverage: 'Low',
    elevationProfile: [800, 1500, 2000],
  },
  W4000: {
    code: 'W4000',
    name: 'Western Hills',
    range: '2001-4000m',
    icon: '⛰️',
    color: '#1976D2',
    climateZone: 'Temperate Arid',
    vulnerabilityIndex: 5.8,
    biodiversity: 'Low',
    glacierCoverage: 'Medium',
    elevationProfile: [2001, 3200, 4000],
  },
  W6000: {
    code: 'W6000',
    name: 'Western Peaks',
    range: '4001m+',
    icon: '🏔️',
    color: '#1565C0',
    climateZone: 'Cold Desert',
    vulnerabilityIndex: 4.7,
    biodiversity: 'Low',
    glacierCoverage: 'High',
    elevationProfile: [4001, 5000, 6000],
  },
};

export const TIME_PERIODS = [
  { value: 'full', label: 'Full Record' },
  { value: 'last30', label: 'Last 30 Years' },
  { value: 'last20', label: 'Last 20 Years' },
  { value: 'last10', label: 'Last 10 Years' },
  { value: 'custom', label: 'Custom Range' },
] as const;

export const MONTHS = [
  'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
  'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'
];
